### ISSUE TITLE
Overriding keybindings is unintuitive and difficult

### ISSUE THREAD

**Issue by adzenith** [atom/atom-keymap#110]
I want to bind `cmd-shift-d` to `atomic-rtags:follow`, but it's stuck as `editor:duplicate-lines`. The former is defined as `atom-workspace atom-text-editor`, whereas the latter is defined as `atom-workspace atom-text-editor:not([mini])`. Why does my custom keybinding not override the built-in one? (Yes, I've discovered that the technical answer is "because its context is more specific".) I feel like this should be easy for me to remedy by myself without reading through issues on Github.

The only solution of which I am aware is to track down every usage of the offending shortcut by using the keybinding resolver, click on it to open the file it's in, search through that file to find the keybinding (because the link doesn't take you to the relevant line), copy and paste its context into my user keymap, and bind the key to `!unset`. Then, if ever any package rebinds this shortcut, I also have to remember and rerun these steps for that shortcut as well. Is this the correct approach? Or is there some simple easy way that I just can't figure out?

Thanks!

**Comment by adzenith** [comment]
I can't actually get `unset!` to work. The keybinding resolver shows three black check marks (the first one corresponding to the `unset!` command). For other commands, it shows one green check mark and grey Xes for commands that weren't run. I'm not sure what's going on.

**Comment by lee-dohm** [comment]
We know that the system is confusing (see https://github.com/atom/atom-keymap/issues/49, https://github.com/atom/atom-keymap/issues/33, https://github.com/atom/atom/issues/6718, among others). We continue to discuss ideas of how to make the keybinding system more approachable while maintaining the flexibility and power of the current system.

`unset!` is only useful when you want to disable a key completely. When you want a key to be bound to a different command than the default, it is unnecessary to use `unset!`.

If a keybinding is winning out over your desired one, such as `editor:duplicate-lines` in your example above, this is what you should do:

1. Find the selector for the winning keybinding
1. Add the selector to your `keymap.cson` if it does not already exist there
1. Add your desired keybinding under that selector in step 2

So, continuing the example, you need to add this to your `keymap.cson`:

```coffee
'atom-workspace atom-text-editor:not([mini])':
  'cmd-shift-d': 'atomic-rtags:follow'
```

Keep in mind that you should only have one instance of each selector in your `keymap.cson` because if you duplicate selectors, [only the last one will be read by the system](https://discuss.atom.io/t/snippets-why-does-only-the-last-snippet-work/18975).

**Comment by dragonxlwang** [comment]
Hi @lee-dohm , following your instruction, I found that in  preference panel -> keybinding, for the same key and selector, I can see the same key mapped to two entries. Is that okay as long as the user (I) defined one wins over the plugin/system one?

![image](https://cloud.githubusercontent.com/assets/15812510/13835964/e88a553a-ebca-11e5-9f1c-a45026e295c9.png)

**Comment by lee-dohm** [comment]
@dragonxlwang Yes, it is. For example, here's the list of what is mapped to <kbd>Tab</kbd> on my installation of Atom:

<img width="1073" alt="screen shot 2016-03-16 at 9 53 00 pm" src="https://cloud.githubusercontent.com/assets/1038121/13836731/86aec69c-ebc1-11e5-96cd-c378f255eba4.png">

We designed the keybinding system so that one could use the same key (or key combination) in different areas of the application or in the same area of the application for different things.

**Comment by dragonxlwang** [comment]
thanks!

But what do you mean by

> in the same area of the application for different things.

?? Shouldn't the behavior in one selector for the same key to be deterministic?

**Comment by lee-dohm** [comment]
While it is not quite deterministic, it is cooperative. In the keybinding documentation it [covers how multiple keybindings can be bound to the same key](https://atom.io/docs/latest/behind-atom-keymaps-in-depth#overloading-key-bindings) and how they cooperate so that if the first key's job isn't applicable, it defers to the next one. Notice that I have, for the exact same selector (in red), three different packages (in blue, green, and orange) mapping four different commands to <kbd>Tab</kbd>:

<img width="1073" alt="comparison" src="https://cloud.githubusercontent.com/assets/1038121/13836876/119cb0d8-ebc3-11e5-90e2-528732342e1d.png">

**Comment by dragonxlwang** [comment]
that makes lots senses. Thanks for explaining!

**Comment by lee-dohm** [comment]
> Does it ensure that user defined key always take more priority than others?

No, CSS specificity states that all things being equal, the last one to be loaded wins. But there are plenty of things that can cause a built-in keybinding to override a user-specified keybinding. One of our long-standing community members, @mark-hahn, has been recommending this tutorial for learning about specificity in CSS:

http://specificity.keegan.st/

**Comment by dragonxlwang** [comment]
> No, CSS specificity states that all things being equal, the last one to be loaded wins. 

But when is the .atom/keymap.cson loaded? I hope it would be loaded last.

**Comment by mark-hahn** [comment]
>  I hope it would be loaded last.

Yes it is, but that doesn't override the specificity rules.  It is treated exactly as CSS rules are treated in a web page.

**Comment by dragonxlwang** [comment]
Thanks @mark-hahn

**Comment by courthead** [comment]
The keybinding system has been confusing an unintuitive for me since the day I installed Atom years ago, and for everyone I've introduced to Atom as well. It's extremely frustrating how difficult it is to accomplish the simplest and most common of tasks: changing a key from one behavior to another.

This morning (on Atom 1.7.3) I wanted to change `ctrl-tab` from `pane:show-next-recently-used-item` to `pane:show-next-item`. By default, the selector is set to `body`, so one would think this is all I need to add to my keymap:

```
'body':
  'ctrl-tab': 'pane:show-next-item'
  'ctrl-shift-tab': 'pane:show-previous-item'
```

But nope, this has the bewildering and completely undesirable result of running both **my** keybinding **and** the default keybinding at the **same time**:

![overridden-keybinding](https://cloud.githubusercontent.com/assets/148083/14942848/c9ac432c-0f7d-11e6-8768-363eeae082d2.png)

Why? No amount of reading the docs makes this behavior intuitive. Identical CSS selectors+properties cannot co-exist, they overwrite each other. So why are my identical keybindings co-existing instead of overwriting?

In order to finally get this simple change working, I had to not only unset the current keybindings in their selector, but then come up with a different selector to set my keybindings:

```
'body':
  'ctrl-tab': 'unset!'
  'ctrl-shift-tab': 'unset!'

'.platform-darwin':
  'ctrl-tab': 'pane:show-next-item'
  'ctrl-shift-tab': 'pane:show-previous-item'
```

I love Atom, but this keybinding nonsense is endlessly frustrating.

**Comment by 50Wliu** [comment]
@courthead your issue is because the MRU keybinding is actually `ctrl-tab ^ctrl`, which needs to be unset separately.  Here's an example of how you should change your keybindings to revert to the original left->right tab switching: https://github.com/atom/atom/issues/11035#issuecomment-192015334

**Comment by courthead** [comment]
Thanks for the info. Turns out you have to use `unset!` not `abort!`.

Anyway, this is just another example of keybindings being extremely difficult to use. What is `^ctrl`? Why do I have to specify `^ctrl` in my custom keymap but it doesn't appear when the key is pressed in the Key Binding Resolver, nor in the keybindings table in the settings, nor when I copy the keybinding from settings? It's almost like it's deliberately intended to mislead and confuse.

**Comment by 50Wliu** [comment]
The missing `^ctrl` is most likely a bug.  What the `^` syntax means is that the command is not executed until the key following the `^` is released.  So `ctrl-tab ^ctrl` would keep cycling through tabs until `ctrl` is released.  See https://github.com/atom/atom-keymap/pull/113 for the PR that added this.

**Comment by derwaldgeist** [comment]
+1 The current system is more than confusing, even for experienced CSS developers like me. The simple reason is that you have to know exactly what the most specific rule is in order to override it. I know know that there's a key resolver, but this wasn't intuitive either. In most other editors, you just have a GUI where you can set key bindings to your liking.

**Comment by thiagocmoraes** [comment]
I was trying to do **exactly** the change @courthead wanted and I got as far as getting the code below done:

```
'body':
  'ctrl-tab': 'pane:show-next-item'
  'ctrl-shift-tab': 'pane:show-previous-item'

```

Figuring out that a Key Resolver existed show me that my rules wasn't being executed, but I had to get to issue tracker to find out what I wanted and even after that, I was only able to do it because someone wanted exactly the same thing. 

Googling returns multiple issues and no place seems authoritative about how to learn about this at all. Can we at least think of providing some commented examples in `keymap.cson` by default. 

That would alleviate the pain.

**Comment by carlgao** [comment]
I was trying to do the exact same thing as @courthead and @thiagocmoraes, and after an hour finally figured out that I needed to put:
```
'body':
  'ctrl-tab': 'unset!'
  'ctrl-shift-tab': 'unset!'

'.platform-darwin':
  'ctrl-tab': 'pane:show-next-item'
  'ctrl-shift-tab': 'pane:show-previous-item'
```
BEFORE 
```

'atom-text-editor.vim-mode:not(.insert-mode)':
  'g u': ''

'atom-text-editor.vim-mode.visual-mode':
  'u': ''

'atom-text-editor':
  'cmd-shift-D': ''
```
in keymap.cson. It actually turns out that anything I put after the 'atom-text-editor' rules gets ignored, I think. Why?? WHY?? I can't believe spent a whole hour on this T_T

**Comment by belgacea** [comment]
+1000

**Comment by wtgee** [comment]
:+1: It is very difficult to do even the most basic keybinding overrides. I shouldn't even have to be looking this up.

**Comment by CreaRo** [comment]
I moved to atom from ST2. I've been stuck at trying to change my key binding for ctrl-up and ctrl-down (scroll up/down line by line) for the past hour, and still can't get it to work! Is there someone who's been able to change the keybinding for this successfully?

**Comment by pdf** [comment]
The keybinding story sucks really hard.  Having tried numerous combinations, `unset!` does not appear to work reliably at all.

Not being able to copy-paste from the keybinding resolver pop-up doesn't help.

Please at least give us `!important` or similar, or just give user keymaps precedence so we don't have to wade through this horrific mess.  It's currently vastly more painful than it needs to be.

**Comment by nathansobo** [comment]
Hey, I hear you guys. I'm currently focused on other pain points but this is on my radar to improve. I originally designed the selector based system in an attempt to make things flexible in the face of different packages written by different people interacting in the same DOM. It may be too flexible.

It's going to take some thinking about how to extend it with a better user interface or replace it in a way that preserves backward compatibility. In the meantime, sorry for the sucky experience. I don't know what else to say right now other than I care but can't drop everything this second to fix it.

If people want to start discussing proposals for how this should ideally work, I'm all ears.

**Comment by mark-hahn** [comment]
The worst part is the bug in cson that it doesn't throw an error when you
have multiple matching properties.  This constantly causes confusion.
Maybe atom could check for this?

**Comment by courthead** [comment]
Thanks for replying @nathansobo! I  think the system needs to be primarily focused on the 99% use-case: overriding some existing keybinding with a new one. That should be easy, intuitive, and reliable for anyone to do, without requiring users to:

- understand Atom's selectors and/or know them by heart
- understand "unset!", "abort!", etc
- guess and check
- browse source code of any kind
- wade through pages of GitHub issues

Ideally, it would be as simple as `key combo --> desired action` and that's it. Yes, there are edge cases where users want multiple actions to fire with one key combo, or a combo to do different things in different places, etc. Those are rare exceptions to the rule, however. Only those particular edge cases should require any special knowledge, or research, or code/config.

**Comment by nathansobo** [comment]
We're taking the advice of some people on this thread in https://github.com/atom/atom/issues/12760, which always gives precedence to user bindings regardless of selector specificity and displays errors when a keymap contains duplicate keys.

I'm hoping that these changes make `unset!` a lot easier to use in the rare cases it's required. Ultimately, a graphical UI for designing bindings may be the ultimate solution, but I'd like to see how people feel after we release these changes in 1.12.0. If it's still a problem, we can reopen this issue.

**Comment by JD719** [comment]
Binding system in Atom is just awful, It needs to be rewritten.

**Comment by lee-dohm** [comment]
@JD719 your comment was deleted as a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it is insulting or derogatory. You may consider this an official warning.

**Comment by Zerim** [comment]
FYI I think changing user keymap settings as the equivalent of an `!important` is a positive change.

However, for me the not loading of duplicate keys was a breaking change. The error also does not specify the offending line member, which makes it very difficult to track down what the actual error is (I was using that key in quite a few different selectors).

Further more the docs at a glance lead you to believe that 'overloading keybindings' is something that is supported, and only in the fine print does indicate that Atom does support executing two commands from a single keybinding (though there still seem to be contradictory statements).

About an hour spent debugging until stumbling across this issue and reading through the intents of the change.

Thank you for the great editor, just sharing my poor experiences with this. Having the error show line number, or even link to the PR, an item in the change log or this issue would have been very helpful.

**Comment by rubimazaki** [comment]
Guys.... What about a simple FUCXXXXkING GUI table???? Why is it so damn impossible to set a keybinding. Going to uninstall ATOM now. 10 minutes after installing... YOUR FAULT!

I just tried to use ATOM. The first thing I do is see if I CAN use it. Number one thing is keybinding - which I like to keep my own THANK YOU.

I have key preferences I keep from the days of visual studio 6.0 (yeah previous millenium :-) ). I don't want to learn Atom's creator's preferences. Current keybindings file editing is not hard, it is IMPOSSIBLE. You want us to keep the (whatever) keybindings you have. 

I am not even going to try.

**Comment by 50Wliu** [comment]
> However, for me the not loading of duplicate keys was a breaking change.

Atom never loaded duplicate keys (the last one would win priority).  It just wasn't obvious until the error notification was added.

If you could please open an issue on atom/atom asking for the line number to be added to the notification, that would be great.

**Comment by dreftymac** [comment]
## Fix broken link to overriding keybindings
* [#issuecomment-197704493](https://github.com/atom/atom-keymap/issues/110#issuecomment-197704493) has a broken link ... fixed below
* [#overloading-key-bindings](http://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/#overloading-key-bindings)

**Comment by nathansobo** [comment]
Thanks! Fixed in the original.

**Comment by phoenixeliot** [comment]
Had the same issue as @courthead, and took a solid 20 minutes to dig enough to find that I needed to also unset the `^ctrl` part. That part in particular needs some better surfacing of why one command is happening instead of another (especially since that particular customization of ctrl-tab seems to be pretty common).

**Comment by lee-dohm** [comment]
We have another method of choosing the behavior of <kbd>Ctrl+Tab</kbd> that doesn't require any knowledge of customizing keybindings seen in the [Atom FAQ](https://discuss.atom.io/c/faq) here:

https://discuss.atom.io/t/i-want-ctrl-tab-to-work-like-it-used-to-how-do-i-do-that/28639

**Comment by vibrunazo** [comment]
I think the best solution for this problem would be to simply change the default snippet for "key" to something else that takes higher priority over all native key bindings everywhere. Instead of simply 'body'.

That way, any new keybinding added in keymap.cson using the snippet (I assume that's how most people add their first hotkeys) will always override all else by default. As opposed to the current behavior, where new keybindings just added by new users might just be lower priority than something else.

Problems could arise from overriding a native keybinding you might later want. But that's a far easier problem to find/debug/fix than the current one. The default comments on keymap.cson already suggests using the Keybind Resolver to look for conflicts.

**Comment by hanslivingstone** [comment]
For anyone else struggling here, I created this package which automatically removes any keybindings (including those from Atom's core) that conflict with what you set in 'keymap.cson': https://atom.io/packages/keymap-control Hope this helps.

**Comment by storypixel** [comment]
@hanslivingstone just installed it, so far so good! I was having trouble when atom decided it wanted ctrl-l but i had it for switching to a pane on the right.

**Comment by uniqss** [comment]
after hours of seaching and testing, I realized that Atom should at least offer a switch to turn off all it's default massing keybindings.
