### ISSUE TITLE
atom-keymap on a react.js & electron.js project, CSS selector not working

### ISSUE THREAD

**Issue by m0g** [atom/atom-keymap#127]
Hi,
I'm trying to use atom-keymap in my own electron based application.
My interface is mostly built with react.js.

I've instantiated atom-keymap in my top component:

```
export default class App extends React.Component {
  componentDidMount() {
    let keymaps = new KeymapManager();
    keymaps.defaultTarget = document.body;
    keymaps.loadKeymap(`${__dirname}/../../keymaps/linux.json`);

    document.addEventListener('keydown', function(event) {
      keymaps.handleKeyboardEvent(event);
    });
  }

  render() {
    return(
      <Provider store={store}>
        <Ansel />
      </Provider>
    );
  }
}
```

Here is my `keymaps/linux.json`:

```
{
  ".picture-diff": {
    "y": "diff:cancel"
  },
  "body": {
    "tab": "core:toggleSidebar",
    "escape": "core:cancel"
  }
}
```

Here is an excerpt of the picture-diff component:

```
  componentDidMount() {
    window.addEventListener('core:cancel', this.props.actions.toggleDiff);
    window.addEventListener('diff:cancel', this.props.actions.toggleDiff);
  }
```

So what is going on here, is that any events that are associated with `body` are executing properly. However every time I'm trying to use the CSS selector for something else than `body` (for instance `.picture-diff`), it doesn't trigger.

Am I missing something here? Is it possible to get atom-keymap to work with react or is it only intended for atom?

Thanks

**Comment by nathansobo** [comment]
It's hard to say exactly what's going on. React implements its own custom event dispatch, so that might be a factor. Make sure that the keymap is getting your events. Check the target of your events, since that's what the keymap will match selectors against. Set a breakpoint with the `debugger` keyword and step through to see what's happening. Unfortunately I don't have the bandwidth to heavily support you in a usage outside of Atom, though in principle there's no reason it shouldn't work.
