### ISSUE TITLE
[win 10] russian keyboard layout: inconvenient dot-keybinding

### ISSUE THREAD

**Issue by yalov** [atom/atom-keymap#179]
[russian_and_english_keyboard_layout.png](https://s11.postimg.org/i6xwz1prn/keyboard.png)

If there is active russian keyboard layout, key binding resolver shows english key: 
`и` → `b`
`т` → `n`
`ь` → `m`
`б` → `,`
`ю` → `.`

But last right key at bottom row (`/? .,`) uses russian layout:
`.` → `.` 
instead of:
`.` → `/`

For example, you want to comment out something, using `Ctrl`+`/`, and you didn't notice, that your active layout is russian. At that case, `Ctrl`+`/` is turning to `Ctrl` + `.` (hotkey for keybinding resolver)
So, instead of commenting out some code,  you see keybinding resolver shows up.

**Comment by nathansobo** [comment]
cc @ungb and and @Ben3eeE for help getting some clarification about what's going on here.

**Comment by Ben3eeE** [comment]
@nathansobo in https://github.com/atom/atom-keymap/pull/151 you changed it so that a-z converts to their latin equivalent, which is great in example russian layouts where users seem to expect this.

The proposed change here is to do the same for symbols because when changing between russian and english layouts the symbols also change position. So the required keystrokes to type for example <kbd>Ctrl-/</kbd> moves to another physical position on the keyboard because they change layouts when typing in the different languages.

**Comment by nathansobo** [comment]
@yalov Is this how other applications handle the Russian layout? Do they always fall back to the U.S. layout equivalent key for every key on the keyboard when matching bindings?

**Comment by yalov** [comment]
@nathansobo I think so. 
Sublime Text falls back to the U.S. layout equivalent key for  `Ctrl` + `/` hotkey.

**Comment by nathansobo** [comment]
Thanks for the report. I'm taking a strategy of detecting non-Latin keyboards by looking at the keycap for the first 4 letters of the home row. If any of these keys are non-Latin, then I fall back to the U.S. layout for modified keystrokes for the entire layout, even if particular symbols fall in the latin range.
