### ISSUE TITLE
Ctrl+<key> uses english keymap instead of french

### ISSUE THREAD

**Issue by StupidUselessAccount** [atom/atom-keymap#197]
Hello,

I use Archlinux, with a french keymap. I updated atom today. Now, when I type code, the french keymap is used. But when I use a shortcut like `ctrl+z` or `ctrl+w`, the english keymap is used (e.g. `ctrl+z` closes the panel). If I switch to an english keymap (`setxkbmap us`), it works as it should, but not when I use a french keymap (`setxkbmap fr`).

I may be linked to https://github.com/andischerer/atom-keyboard-localization/issues/146

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You may want to subscribe to https://bugs.archlinux.org/task/50357 for updates.
