### ISSUE TITLE
All bindings use a QWERTY layout instead of the one in use

### ISSUE THREAD

**Issue by BenjaminNavarro** [atom/atom-keymap#199]
Since a week or so all my key bindings are mapped to a qwerty layout even if I use an azerty one.

The editor works just fine (I can type text according to my layout) but for example if I want to trigger the ctrl-a shortcut I have to press ctrl-q. 

If in my keymap.cson I add: 
`'atom-workspace atom-text-editor':
  'ctrl-q': 'core:select-all'`
I can use ctrl-a to select everything.

Is there a way to fix this without remapping everything by myself? I have no problem with other text editors so the problem is not bound to my system (Archlinux)

**Comment by Ben3eeE** [comment]
What is the output of `atom --version` and `apm --version`.

**Comment by BenjaminNavarro** [comment]
`atom --version
Atom    : 1.12.7
Electron: 1.4.12
Chrome  : 53.0.2785.143
Node    : 6.5.0
`
`apm --version
(node:10126) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
apm  1.14.1
npm  4.0.5
node 7.2.1
python 3.5.2
git 2.11.0
`

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You may want to subscribe to https://bugs.archlinux.org/task/50357 for updates.

**Comment by BenjaminNavarro** [comment]
Thanks for pointing me to the origin of the problem, I'll look into it

**Comment by Ben3eeE** [comment]
@BenjaminNavarro Some users have reported that `atom-editor-bin` in the AUR works for them since it seems to use the correct Electron version.

**Comment by StupidUselessAccount** [comment]
Electron have been updated on arch and the bug disappeared for me.
