### ISSUE TITLE
it keymap error

### ISSUE THREAD

**Issue by Donatomar** [atom/atom-keymap#241]
Hi all,
I noticed some day ago that I cant use "|" in atom with italian keyboard on mac-osx.
When I hod "|" button atom print ">".
How can i resolve this issue?
Thanks

### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Hi all,
I noticed some day ago that I cant use "|" in atom with italian keyboard on mac-osx.
When I hod "|" button atom print ">".
How can i resolve this issue?
Thanks
### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**
Always

### Versions
1.38.2

**Comment by rsese** [comment]
Thanks for the report!  Can you fill in the issue template?  The format is super useful for us when triaging issues (e.g. see how this issue was filled out for reference: https://github.com/atom/atom/issues/19168).

Also, when you say "I noticed some day ago", do you mean that this used to work ok but stopped working recently?  Do you remember if you were using a different version of Atom before when things worked and then you started seeing this behavior after updating Atom?
