### ISSUE TITLE
Handle the Windows Key

### ISSUE THREAD

**Issue by ccoenen** [atom/atom-keymap#55]
I would love to bind some actions on the windows key, but apparently, it does not resolve right now.

Key Binding Resolver will show "win" when i press the windows key, but once it Try something like win-A, it will display just "a".

**Comment by flashlee** [comment]
@nathansobo on linux (Fedora 23) it seems impossible to handle winkey. Press and hold button don`t give an event at all (and some of combinations like win+a, win+space, win+v, everything that makes Fedora doing something on pressing combination).
If press win+G for example (here is not such shortcut for Fedora), then keyboard event returns keyCode of "G", but with metaKey=true.
KeyboardEvent {isTrusted: true, location: 0, ctrlKey: false, shiftKey: false, altKey: false…}
altKey: false
bubbles: true
cancelBubble: false
cancelable: true
charCode: 0
code: "KeyG"
ctrlKey: false
currentTarget: null
defaultPrevented: false
detail: 0
eventPhase: 0
isTrusted: true
isTrusted: true
keyCode:71
keyIdentifier: "U+0047"
keyLocation: 0
location: 0
metaKey: true
path: Array[4]
repeat: false
returnValue: true
shiftKey: false
sourceCapabilities: InputDeviceCapabilities
srcElement: body
target: body
timeStamp: 10081.365000000002
type: "keydown"
view: Window
which: 71
__proto__: UIEvent

**Comment by ccoenen** [comment]
This is another thing that might have been fixed by @nathansobo's https://github.com/atom/atom/pull/12697 !

Now, when I hit <kbd>Win</kbd>+<kbd>n</kbd> (it's becoming increasingly hard to find free shortcuts - "a" has been taken since I opened this ticket :D ), The Key binding resolver displays `cmd-n` so while it does not display "win" but this can be used to map the windows key!

I tried this with

```
'atom-text-editor':
  'cmd-n': 'editor:newline'
```

in my `keymap.cson` and it worked :D - So: another ticket down due to a very appreciated patch :)

(tested on Windows 10 / 1607 64bit)

**Comment by 50Wliu** [comment]
@nathansobo: I feel that the Windows key should be bound to `win` instead of `cmd`.

**Comment by nathansobo** [comment]
>  I feel that the Windows key should be bound to win instead of cmd

@50Wliu Yeah, that's something I've thought about. My concern is that currently a keystroke description works on every platform, whereas if we change the name of the windows key all of a sudden you'll have to have a bunch of platform-specific bindings. Perhaps that's inevitable considering how different the Windows key is.

**Comment by ccoenen** [comment]
As far as I know, the windows key is referred to as "super" on linux systems. Is cmd === super?

**Comment by nathansobo** [comment]
> Is cmd === super?

I guess the larger question is how much it matters that these keys have a slightly incorrect name. If we call the key `super` on Linux and `win` on Windows, I guess that's more "respectful" of the platform or something, but it also just feels like an arbitrary distinction to me that makes it more likely that bindings will be missing on a platform. If a package author just cares about one platform and writes some bindings, there's a good chance they'll work on another platform unless they're already shadowed by the OS. That's the situation where it's unclear to me. Is it *harmful* to bind the windows key in some cases, or are we just upset that the name is wrong? If it's just about the name, how should the yuckiness of an inaccurate name be weighed against the downsides of fragmentation? These are all honest questions. I don't have a *super* strong viewpoint here.

**Comment by ccoenen** [comment]
_The following is sadly not a solution post. It's a train of thought post that might or might not lead to a better solution. Sorry._

The regular <kbd>win</kbd>+<kbd>_something_</kbd> shortcuts are super densely packed in Windows 8 and later. Pretty much all the letters are used. Some of which are more widely known (and useful) like <kbd>win</kbd>+<kbd>D</kbd> (show desktop) and <kbd>win</kbd>+<kbd>P</kbd> (presentation settings), or some obscure things like <kbd>Win</kbd>+<kbd>H</kbd> (share? seriously?).

If a key was used by both (OS and atom) which one would be shadowed? Would atom get the event or would the OS get it?

* **win and cmd and super are seperate things:** fragmentation valley. _:arrow_forward: not ideal_
* **win === cmd and atom gets the event:** I run the risk of installing a plugin that uses <kbd>Win</kbd>+<kbd>D</kbd>, and just like that I can't summon my desktop any more. _:arrow_forward: not ideal_
* **win === cmd and the OS gets the event:** We're back at fragmentation valley regardless of the name in the keymap. We get some of the defined shortcuts, but not all. _:arrow_forward: not ideal_

So I guess we'd have to pick which solution is the least shitty one? Judging from pure gut feeling, I think the third one is "the least worst of all".

**Comment by nathansobo** [comment]
I guess if we called the key `win` explicitly and could preempt the OS with bindings, that might be ideal because people could selectively override Windows bindings they don't care about. But it seems like binding `win` in application-specific ways is not a common usage pattern... am I wrong? If that's true it seems like the naming of the key would be low priority because Windows users don't really expect to be able to use it anyway.

**Comment by ccoenen** [comment]
Win for applications is _super_ rare. I can only think of one program that uses it, and I don't like it :D

**Comment by michael-lumley** [comment]
Just to bring this thread back to the top. I have a super specific use case: I'd like to be able to use <kbdWin</kbd>-<kbd>(arrow)</kbd> to sling my tabs back and forth between panes. I'd like to specifically bind to that because I also use <kbdWin</kbd>-<kbd>(arrow)</kbd> to sling windows around my desktop, so my instinctual response on Atom is the same. I'm guessing there are reasons this can't be done (i.e. whether the OS or Atom gets the event) but it would be really nice to set up atom with the same kinds of bindings as I use on the desktop.

**Comment by nathansobo** [comment]
@michael-lumley You might try experimenting with [adding a custom keystroke resolver](https://github.com/atom/atom-keymap/blob/d42d6d0eede8b5c6eeddc9711992cd9f200167dd/src/keymap-manager.coffee#L676). You could log out the event objects inside the resolver to see if there's any state you could use to determine it's the windows key. If I'm remembering correctly, we pass both keyup and keydown events to custom resolvers. You may need to keep some state that tracks when the windows key is pressed and released in order to pull this off.

If you find a working solution, you might consider opening a PR. This repo is all still CoffeeScript unfortunately, but it might not be too complicated. We'd definitely need some test coverage before merging anything.

**Comment by nathansobo** [comment]
@Ben3eee reminded me that we do already resolve this key to `win`, but that we don't always get events if the OS captures a binding. If that's the case there's not much we can do. Sorry for the misinformation!

**Comment by Ben3eeE** [comment]
> reminded me that we do already resolve this key to `win`.

This key is `event.metaKey` which we resolve to `cmd` on all platforms:

https://github.com/atom/atom-keymap/blob/d42d6d0eede8b5c6eeddc9711992cd9f200167dd/src/helpers.coffee#L250-L252

But when there is an OS level binding for the keystroke we don't receive the events and can't resolve it. Since we don't receive the events we can't send them out to a public keystroke resolver.

**Comment by charry223** [comment]
Sharing my experience to say,if someone need office product keys,you can go to https://www.vanskeys.com/ to got.I'm here to buy a key, a hundred percent genuine.

**Comment by ccoenen** [comment]
can we get @nathansobo  to get rid of this spam posting (and, if he likes, this post by me, too)

**Comment by Ben3eeE** [comment]
Thanks @ccoenen I deleted the spam comment and your comment.
