### ISSUE TITLE
Unsetting a key doesn't appear to work with complex selector

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom-keymap#79]
Ref: atom/markdown-preview#114

I was experimenting with my keybindings to unmap the default Markdown Preview key:

```coffee
'atom-workspace, atom-workspace atom-text-editor':
  'ctrl-shift-M': 'markdown-preview:toggle'
```

and set a new, grammar-scoped key:

```coffee
'atom-text-editor[data-grammar="source gfm"]':
  'ctrl-shift-M': 'markdown-preview:toggle'
```

So I added the following to my `keymap.cson`:

```coffee
'atom-workspace, atom-workspace atom-text-editor':
  'ctrl-shift-M': 'unset!'
'atom-text-editor[data-grammar="source gfm"]':
  'ctrl-shift-m': 'markdown-preview:toggle'
```

which, in theory, should make it so that <kbd>Ctrl+Shift+M</kbd> should only activate the Markdown Preview when a GFM text editor is focused. But if I do the following:

1. With the keymap modification above active, open a Markdown file
1. Focus the tree view
1. Press <kbd>Ctrl+Shift+M</kbd>

**Expected:** Markdown Preview is **not** displayed
**Actual:** Markdown Preview **is** displayed

Here's what I see in the Keybinding Resolver:

![screen shot 2015-05-11 at 8 21 40 am](https://cloud.githubusercontent.com/assets/1038121/7568306/d4e8aa58-f7b6-11e4-8402-5336c32838a0.png)

**Comment by lee-dohm** [comment]
Ref: https://discuss.atom.io/t/how-to-replace-a-keymap-binding/16834

I have another case where this occurs. This is on OS X (change the mapped key to <kbd>Ctrl+J</kbd> for Linux/Windows):

```coffee
'atom-workspace atom-text-editor:not([mini])':
  'cmd-j': 'unset!'
'atom-text-editor':
  'cmd-j': 'core:move-left'
```

The person posting the issue wants to use <kbd>Cmd/Ctrl+J</kbd> to move left in all text editors, mini or not. So the above should unmap `core:join-lines` from <kbd>Cmd/Ctrl+J</kbd> and allow the less specific `atom-text-editor` to take precedence. But it doesn't:

![screen shot 2015-05-15 at 5 49 27 pm](https://cloud.githubusercontent.com/assets/1038121/7664016/69174e7e-fb2b-11e4-9a23-a64b814ca7a2.png)

The unset `core:join-lines` command still executes and `core:move-left` does not.

**Comment by lee-dohm** [comment]
A workaround is documented on the Discuss topic listed above.

**Comment by fgimian** [comment]
Your workaround saved me too, thank you! But sadly, this doesn't still resolve the case where you may wish to disable a key mapping completely.  I really wish `!unset` would work as documented since it is a neat implementation.

**Comment by fgimian** [comment]
Okies, I have a true workaround for disabling a keyboard shortcut.  Simply set to an in-existent command:

```
'atom-workspace atom-text-editor:not([mini])':
  'ctrl-shift-D': 'bla'
```

You may wish to choose a more suitable dummy command name, hehe :smile:

**Comment by izuzak** [comment]
I'm seeing some strange behavior with `unset!` as well, even with selectors which are not complex.

Example: the tree view has [this keybinding](https://github.com/atom/tree-view/blob/667ae1f2cc5da943a3ad7edd2f142545566b977f/keymaps/tree-view.cson#L1-L2):

```cson
'.platform-darwin':
  'cmd-\\': 'tree-view:toggle'
```

And I can't unset this by adding this to my keymap.cson file:

```cson
'.platform-darwin':
  'cmd-\\': 'unset!'
```

![toggle](https://cloud.githubusercontent.com/assets/38924/7809697/7061f9b2-039c-11e5-8a31-b54fe03f319c.gif)

As far as I can tell, keymap manager is not triggering the command here (`dispatchCommandEvent` is not called), but something else is triggering the behavior. Using `abort!` instead of `unset!` or adding `event.preventDefault()` to [how `unset!` is handled](https://github.com/atom/atom-keymap/blob/d2e2455939ff852ebf15503c6faca3d10069c206/src/keymap-manager.coffee#L436-L437) fixes things -- the `tree-view:toggle` command doesn't trigger when I press `cmd-\`

**Comment by nathansobo** [comment]
Taking a look at this now.

**Comment by nathansobo** [comment]
This is happening because there is an application menu item that is still getting triggered via the operating system's default key binding support. Currently, the `unset!` command simply continues the search from the ancestor of the unset element. If no matching binding is found however, the browser still handles the keyboard event, which ends up running the command out of the application menu.

My preferred fix for this would be to be much smarter about how key bindings are shown in the application menu. But this is tricky because in order to determine whether or not a given binding was unset, we may need to run an arbitrary selector match against a specific element. Currently we just decide on the menu bindings in a global way.

So as a simpler solution, I'm just going to call `preventDefault()` whenever we encounter an `unset!` binding. If we continue the search and find another command, we'll call `preventDefault()` again, which shouldn't be a problem. If we don't find a command, the command from the application menu won't be invoked.

**Comment by izuzak** [comment]
Reopening since https://github.com/atom/atom-keymap/commit/d0af390501ed739c3de9346e879bc3a3524e03b4 was reverted in https://github.com/atom/atom-keymap/commit/46d726e3e2b30c65ecd3fb3765a2a720e98743f1.
